language: node_js
node_js:
- 12
script:
- npm run build
cache:
  directories:
  - node_modules
  - ".next"
deploy:
  provider: heroku
  api_key:
    secure: czKZNfN/pHMQGHEzm3d4d3dDXd53oy52D5oiZBONOGe2HJ2PuGfShtOEApIucEk/8oWDV670mmVLv39bAnTkAhsuUmoD6nDeAITRu0wkzYtGi7Ys1i3VrsOufJSSyUw/36BeLO+4h+bXtuw9ljsctbOIFQyBdWi266Pg5Tzm/PYGbR3lRqu7uZ/SR6GbQKOOCdHEXYWHmYO3Atd6hHBrC5YO0XT5lcB4qLMNHj0ZpFVMcnNmP6ntDEVJfvABJK7Wv12smMSxjoF7iGOnb0FMgMMEhF2iD+6yHNEgeZZsh+E7XA9CtIUYV+OYYuiM19oRNrU/aJZuNJfoyymdw//3J1oAmat0ons5qmRx0P+Eh+wFBLLKObthcKvOlaZPttgY+nRPF+6OfrGFaRg5gfjOUs9tnNKaFQSBmeh17afFrDeTtd8Rjh3bcTmgLGpBvlU9YvmJBozhJwaA5eMtkF5JSmKUwy7xKC9HH1/2sKFu45hKualWe4xP33sZhatqmTqSJzs12cbD20IGGWeK3LxCFiPz7VV+L/Yhm1PHxfTq0shgBNvFBiNr4buO8acfpp7CMKfmHKcwaCnmDhuL3Du73BAdLQVJmbDusT1LmMETRioUm30+yX9Fp2Cjv4fhlhjsHDphswbKDaTCfcY5Olzed8sT/MZlqBGeGsquNxqiuwU=
  app: docontra-next-starter
  on:
    repo: petersonwpm/next-starter
  skip_cleanup: 'true'
