---
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo 'Installing dependencies'
      - npm ci
  pre_build:
    commands:
      - echo > .env
      - echo 'PORT=9999' >> .env
      - env >> .env
  build:
    commands:
      - echo 'Building nextJS'
      - npm run build
artifacts:
  files:
    - appspec.yml
    - buildspec.yml
    - .next/**/*
    - node_modules/**/*
    - package.json
    - package-lock.json
    - pages/**/*
    - public/**/*
  discard-paths: no
...
