version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            - run: npm test
            - run:
              name: Creating Artifacts
              command: |
                mkdir /tmp/artifact
                tar -cvf /tmp/artifact/next.tar .
            - store_artifacts:
              path: /tmp/artifact/next.tar
              destination: artifact_name
workflows:
    build-and-test:
      jobs:
        - build-and-test
